# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulates distribution of the gaussian statistics
#'
#' @param t_len           Integer. Length of time series for analysis.
#' @param n_ts        Integer. Number of time series.
#' @param sim_runs    Integer. Number of simulations needed to produce the quantiles.
#' @param gset        A double vector of location-bandwidth points (u_1,...,u_n,h_1,...h_n).
#' @param n           Integer. The number of location-bandwidth points in gset.
#' @param sigma_vec   A double vector of the sqrt of long-run variances.
#' @param deriv_order Integer. Order of the derivative of the trend that is investigated.
#'                    Default is 0 => we analyse whether the trend itself >< than 0.
#' @param epidem      Boolean. Equal to true in cases we are fitting epiemic model. Default is false.
#' 
#' @return Phi_vec A double vector of length sim_runs that consists of the calculated Gaussian statistic for each simulation run
simulate_gaussian <- function(t_len, n_ts, sim_runs, gset, n, sigma_vec, deriv_order = 0L, epidem = FALSE) {
    .Call(`_multiscale_simulate_gaussian`, t_len, n_ts, sim_runs, gset, n, sigma_vec, deriv_order, epidem)
}

#' Calculates the statistics (pairwise and overall) in case of multiple time series
#'
#' @param t_len       Integer. Length of time series for analysis.
#' @param n_ts        Integer. Number of time series.
#' @param data        Double matrix t_len x n_ts. Each column consists of one time series.
#' @param gset        A double vector of location-bandwidth points (u_1,..., u_n, h_1, ...h_n).
#' @param n           Integer. t_lenhe number of location-bandwidth points in gset.
#' @param sigma_vec   A double vector of length n_ts of the sqrt of long-run variances.
#' @param deriv_order Integer. Order of the derivative of the trend that is investigated.
#'                    Default is 0 => we analyse whether the trend itself >< than 0.
#' @param epidem      Boolean. Equal to true in cases we are fitting epiemic model. Default is false.
#' 
#' @return stat       A double matrix of pairwise multiscale statistics Psi_ij.
#' @return vals_cor   Matrix with n rows and n_ts * (n_ts - 1) / 2 columns where each column
#'                    contains values of the normalised Kernel averages in order to be able to perform 
#'                    the test on every separate interval.
compute_multiple_statistics <- function(t_len, n_ts, data, gset, n, sigma_vec, deriv_order = 0L, epidem = FALSE) {
    .Call(`_multiscale_compute_multiple_statistics`, t_len, n_ts, data, gset, n, sigma_vec, deriv_order, epidem)
}

#' Calculates statistics in case of one time series
#'
#' @param t_len           Integer. Length of time series for analysis.
#' @param data        Double vector of length t_len that consists the time series for analysis.
#' @param gset        A double vector of location-bandwidth points (u_1,...,u_n,h_1,...h_n).
#' @param n           Integer. The number of location-bandwidth points in gset.
#' @param sigma       Double. Equal to the sqrt of the long-run variance.
#' @param deriv_order Integer. Order of the derivative of the trend that is investigated.
#'                    Default is 0 => we analyse whether the trend itself >< than 0.
#' 
#' @return stat       A double matrix of pairwise multiscale statistics Psi_ij.
#' @return vals       A double vector of length n of kernel averages (sign included).
#' @return vals_cor   A double vector of absolute value of normalized kernel averages with
#'                    correction \eqn{(abs(\phi(u_1,h_1)/sigmahat) - \lambda(h_1),...,abs(\phi(u_n,h_n)/sigmahat) - \lambda(h_n))}
#' @return stat       Double. Our multiscale statistics calculated as max(vals_cor).
compute_statistics <- function(t_len, data, gset, n, sigma, deriv_order) {
    .Call(`_multiscale_compute_statistics`, t_len, data, gset, n, sigma, deriv_order)
}

