# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_gaussian <- function(t_len, n_ts, sim_runs, gset, ijset, sigma, deriv_order = 0L) {
    .Call(`_multiscale_simulate_gaussian`, t_len, n_ts, sim_runs, gset, ijset, sigma, deriv_order)
}

compute_multiple_statistics <- function(t_len, n_ts, data, gset, ijset, sigma) {
    .Call(`_multiscale_compute_multiple_statistics`, t_len, n_ts, data, gset, ijset, sigma)
}

compute_single_statistics <- function(t_len, data, gset, sigma, deriv_order) {
    .Call(`_multiscale_compute_single_statistics`, t_len, data, gset, sigma, deriv_order)
}

